#!/usr/bin/env bash
# this is the 12th task that i m doing now
#!/usr/bin/env bash                                                                                                                                                         
# this is the 12th task that i m doing now                                                                                                                                  
 while IFS= ":" read $USERNAM $PASSWORD $UID $GID #HOME $COMMAND/SHELL;
	  do
		                  echo " the $NAME is part $GID gang"                                                                                                                         
				                                                                                                                                                                              
				                          echo "lives in homr directory and rides $COMMAND/$SHELL"                                                                                             
							                                                                                                                                                                              
	                                                  echo "$UID's place is protected by password $PASSWORD"    
		          				 echo"more user info about the user here: $'USER ID INFO"   												                                                                                                                                     		                                  done< /etc/passwd                                                                                                                           
																				  ~                                                 i
