#!/usr/bin/env bash                                                                                                                                                         
# this was the difficult part                                                                                                                                               
while IFS=":" read -r username password uid gid info home shell; 
do                                                                                                         
  echo "the user $username is part of $gid gang,"\"lives in $home and ides #shell"\"uid's is place protected by the passcode $passwd"\ "more info about the user here:$info"                                                                                                                       
done<"/etc/passwd"     
