#!/usr/bin/env bash
# this is the 11th task i hope it get done quikly
while IFS=: read -r username _ uid _ _ home _; do
	    echo "Username: $username"
	        echo "User ID: $uid"
		    echo "Home Directory: $home"
		        echo
		done < "/etc/passwd"
