#!/usr/bin/env bash                                                                                                                                                         
# i m going to finish it                                                                                                                                                    
IFS=":"                                                                                                                                                                     
# Open the /etc/passwd file for reading                                                                                                                                     
while read -r username password uid gid info home shell; do                                                                                                                 
	            # Display the username and home directory                                                                                                                       
		                    echo "Username: $username"                                                                                                                                  
				                        echo "Home Directory: $home"                                                                                                                            
							                        echo "---------------------"                                                                                                                        
										                done < /etc/passwdIFS=":"   
