#!/usr/bin/env bash
# is is the only one that i got stuck                                                                                                                                     
while IFS=':' read -r username password uid gid info home shell; 
do                                                                                                                       
        echo "the user $username is part of $gid gang"                                                                                                                             
        echo "lives in $home and rides $shell"                                                                                                                                   
        echo "$uid's place is protected by the passcode $password"                                                                                                                         
        echo "more info about the user is here: $info"                                                                                                                        
done </etc/passwd  
