#!/usr/bin/env bash
#this is the fourth task
count=1
while [ $count -le 10 ]
do
	if [ $count -eq 9  ]
	then 
		echo "Best School Hi"
	elif [ $count -eq 10 ]
	then
		echo "Best School"
	else
		echo "Best School"
	fi
	((count++))
done
