#!/usr/bin/env bash
#this is the fourth task 
count=0
while [ $count -lt 10 ]
do
    if [ $count -eq 9 ]
    then
        echo "Best School"
    elif [ $count -eq 10 ]
    then
        echo "Hi"
    fi

    ((count++))
done 
