#!/usr/bin/env bash
# I m going to 7th tase
hours=0
minutes=1
count=1

while [ $count -le 70 ]
do
	    printf "%02d:%02d\n" $hours $minutes
	        ((minutes++))

		    if [ $minutes -eq 60 ]
			        then
					        ((hours++))
						        minutes=0
							    fi

							        if [ $hours -eq 13 ]
									    then
										            hours=1
											        fi

												    ((count++))
											    done | head -n 70
	
