#!/usr/bin/env bash
# i m going to task nine 
if [ -e "school" ]
then 
	echo "school file exists"
fi
if [ -s "school" ]
then
	echo "school file is not empty"
else
	echo "school file is empty"
fi
if [ -f "school" ]
then
	echo "school is a regular file"
else
	echo "school file does not exist"
fi
